config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'recipes/index', to: 'recipes#public'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'recipes#public'
  resources :users do
    resources :recipes, except: :update do
      resources :recipe_foods
    end
  end
  resources :shopping_list
  resources :foods, except: :update
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Strawberry Gem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
    <div class="logo">
    Strawberry Gem
    </div>
    <div class="elements">
    <% if user_signed_in? %>
      <%= link_to  "Recipes List",  user_recipes_path(current_user.id) ,class:"decoration"%>
      <%= link_to  "Food List", foods_url,class:"decoration" %>
      <%= link_to  "Shopping List", shopping_list_index_path	,class:"decoration" %>
      <%= link_to "Public Recipes", recipes_index_path,class:"decoration" %>
      <%= link_to "Add Recipe", new_user_recipe_path(user_id: current_user.id),class:"decoration" %>
      <%= link_to "Add food", new_food_path %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete,class:"decoration" %>
    <% else %>
      <%= link_to "Public Recipes", recipes_index_path,class:"decoration" %>
      <%= link_to  "Sign up", new_user_registration_path,class:"decoration" %>
      <%= link_to "Login", new_user_session_path,class:"decoration" %>
    <% end %>
    </div>
    </header>
    <div class="main-wrapper">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>